[package]

name = "gidsort"
version = "0.0.1"
authors = ["Jonathan Giddy <jongiddy@gmail.com>"]


[dependencies]

gcd = "1.1.0"
quickcheck = "0.4.1"


[dev-dependencies]
glidesort = "0.1.2"
rand = "0.3.15"
